### ISSUE TITLE
db:reset migration issue

### ISSUE THREAD

**Issue by adrianmcli** [Jebbie87/jungle_rails#1]
Getting errors on running `bin/rake db:reset` for the first time. It seems like the problem is in your `seeds.rb` file (within the `\db` folder). I encountered two errors:

1. Password is too short (needs to be at least 5 characters long).
2. Password confirmation field is missing.

The fix is to simply change to a longer password and add a password_confirmation field to your two seed users. This starts on [line 143](https://github.com/Jebbie87/jungle_rails/blob/master/db/seeds.rb#L143)

```ruby
user1 = User.create!({
  first_name: 'Jebbie',
  last_name: 'Chang',
  email: 'jebbie@chang.com',
  password: 'test'  # this is the problem
})
```

Replace it with this:

```ruby
user1 = User.create!({
  first_name: 'Jebbie',
  last_name: 'Chang',
  email: 'jebbie@chang.com',
  password: 'password',
  password_confirmation: 'password'
})
```

And don't forget to do it with the other user too.

**Comment by Jebbie87** [comment]
The issue has been fixed and I changed the password field in the second user. Added the password_confirmation fields for both users
